// Generated by sprotodump. DO NOT EDIT!
// source: /home/mengmeng/slegend_server/work/proto/prolegend.sproto

using System;
using Sproto;
using System.Collections.Generic;

namespace prolegendType{ 
	public class equiprefine : SprotoTypeBase {
		private static int max_field_count = 2;
		
		public class request : SprotoTypeBase {
			private static int max_field_count = 2;
			
			
			private Int64 _equipid; // tag 0
			public Int64 equipid {
				get { return _equipid; }
				set { base.has_field.set_field (0, true); _equipid = value; }
			}
			public bool HasEquipid {
				get { return base.has_field.has_field (0); }
			}

			private Int64 _propid; // tag 1
			public Int64 propid {
				get { return _propid; }
				set { base.has_field.set_field (1, true); _propid = value; }
			}
			public bool HasPropid {
				get { return base.has_field.has_field (1); }
			}

			public request () : base(max_field_count) {}

			public request (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					case 0:
						this.equipid = base.deserialize.read_integer ();
						break;
					case 1:
						this.propid = base.deserialize.read_integer ();
						break;
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				if (base.has_field.has_field (0)) {
					base.serialize.write_integer (this.equipid, 0);
				}

				if (base.has_field.has_field (1)) {
					base.serialize.write_integer (this.propid, 1);
				}

				return base.serialize.close ();
			}
		}


		public class response : SprotoTypeBase {
			private static int max_field_count = 2;
			
			
			private Int64 _result; // tag 0
			public Int64 result {
				get { return _result; }
				set { base.has_field.set_field (0, true); _result = value; }
			}
			public bool HasResult {
				get { return base.has_field.has_field (0); }
			}

			private string _logger; // tag 1
			public string logger {
				get { return _logger; }
				set { base.has_field.set_field (1, true); _logger = value; }
			}
			public bool HasLogger {
				get { return base.has_field.has_field (1); }
			}

			public response () : base(max_field_count) {}

			public response (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					case 0:
						this.result = base.deserialize.read_integer ();
						break;
					case 1:
						this.logger = base.deserialize.read_string ();
						break;
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				if (base.has_field.has_field (0)) {
					base.serialize.write_integer (this.result, 0);
				}

				if (base.has_field.has_field (1)) {
					base.serialize.write_string (this.logger, 1);
				}

				return base.serialize.close ();
			}
		}


		
		private Int64 _equipid; // tag 0
		public Int64 equipid {
			get { return _equipid; }
			set { base.has_field.set_field (0, true); _equipid = value; }
		}
		public bool HasEquipid {
			get { return base.has_field.has_field (0); }
		}

		private Int64 _propid; // tag 1
		public Int64 propid {
			get { return _propid; }
			set { base.has_field.set_field (1, true); _propid = value; }
		}
		public bool HasPropid {
			get { return base.has_field.has_field (1); }
		}

		public equiprefine () : base(max_field_count) {}

		public equiprefine (byte[] buffer) : base(max_field_count, buffer) {
			this.decode ();
		}

		protected override void decode () {
			int tag = -1;
			while (-1 != (tag = base.deserialize.read_tag ())) {
				switch (tag) {
				case 0:
					this.equipid = base.deserialize.read_integer ();
					break;
				case 1:
					this.propid = base.deserialize.read_integer ();
					break;
				default:
					base.deserialize.read_unknow_data ();
					break;
				}
			}
		}

		public override int encode (SprotoStream stream) {
			base.serialize.open (stream);

			if (base.has_field.has_field (0)) {
				base.serialize.write_integer (this.equipid, 0);
			}

			if (base.has_field.has_field (1)) {
				base.serialize.write_integer (this.propid, 1);
			}

			return base.serialize.close ();
		}
	}


	public class handshake : SprotoTypeBase {
		private static int max_field_count = 1;
		
		public class response : SprotoTypeBase {
			private static int max_field_count = 1;
			
			
			private string _msg; // tag 0
			public string msg {
				get { return _msg; }
				set { base.has_field.set_field (0, true); _msg = value; }
			}
			public bool HasMsg {
				get { return base.has_field.has_field (0); }
			}

			public response () : base(max_field_count) {}

			public response (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					case 0:
						this.msg = base.deserialize.read_string ();
						break;
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				if (base.has_field.has_field (0)) {
					base.serialize.write_string (this.msg, 0);
				}

				return base.serialize.close ();
			}
		}


		
		private string _msg; // tag 0
		public string msg {
			get { return _msg; }
			set { base.has_field.set_field (0, true); _msg = value; }
		}
		public bool HasMsg {
			get { return base.has_field.has_field (0); }
		}

		public handshake () : base(max_field_count) {}

		public handshake (byte[] buffer) : base(max_field_count, buffer) {
			this.decode ();
		}

		protected override void decode () {
			int tag = -1;
			while (-1 != (tag = base.deserialize.read_tag ())) {
				switch (tag) {
				case 0:
					this.msg = base.deserialize.read_string ();
					break;
				default:
					base.deserialize.read_unknow_data ();
					break;
				}
			}
		}

		public override int encode (SprotoStream stream) {
			base.serialize.open (stream);

			if (base.has_field.has_field (0)) {
				base.serialize.write_string (this.msg, 0);
			}

			return base.serialize.close ();
		}
	}


	public class package : SprotoTypeBase {
		private static int max_field_count = 2;
		
		
		private Int64 _type; // tag 0
		public Int64 type {
			get { return _type; }
			set { base.has_field.set_field (0, true); _type = value; }
		}
		public bool HasType {
			get { return base.has_field.has_field (0); }
		}

		private Int64 _session; // tag 1
		public Int64 session {
			get { return _session; }
			set { base.has_field.set_field (1, true); _session = value; }
		}
		public bool HasSession {
			get { return base.has_field.has_field (1); }
		}

		public package () : base(max_field_count) {}

		public package (byte[] buffer) : base(max_field_count, buffer) {
			this.decode ();
		}

		protected override void decode () {
			int tag = -1;
			while (-1 != (tag = base.deserialize.read_tag ())) {
				switch (tag) {
				case 0:
					this.type = base.deserialize.read_integer ();
					break;
				case 1:
					this.session = base.deserialize.read_integer ();
					break;
				default:
					base.deserialize.read_unknow_data ();
					break;
				}
			}
		}

		public override int encode (SprotoStream stream) {
			base.serialize.open (stream);

			if (base.has_field.has_field (0)) {
				base.serialize.write_integer (this.type, 0);
			}

			if (base.has_field.has_field (1)) {
				base.serialize.write_integer (this.session, 1);
			}

			return base.serialize.close ();
		}
	}


}


namespace Protocol{ 
	public class prolegend {
		public static readonly ProtocolFunctionDictionary Protocol = new ProtocolFunctionDictionary ();
		static prolegend() {
			Protocol.SetProtocol<equiprefine> (equiprefine.Tag);
			Protocol.SetRequest<prolegendType.equiprefine.request> (equiprefine.Tag);
			Protocol.SetResponse<prolegendType.equiprefine.response> (equiprefine.Tag);

			Protocol.SetProtocol<handshake> (handshake.Tag);
			Protocol.SetResponse<prolegendType.handshake.response> (handshake.Tag);

		}

		public class equiprefine {
			public const int Tag = 2;
		}

		public class handshake {
			public const int Tag = 1;
		}

	}
}
